apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: COMMENTO_ORIGIN
              value: http://commento.example.com:8080
            - name: COMMENTO_PORT
              value: "8080"
            - name: COMMENTO_POSTGRES
              value: postgres://postgres:postgres@db:5432/commento?sslmode=disable
          image: hellifiknow/commento-multi-arch:latest
          imagePullPolicy: ""
          name: server
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
